# Application info
application.name=@project.artifactId@
build.version=@project.version@
build.timestamp=@maven.build.timestamp@

# logs: TRACE DEBUG INFO WARN ERROR FATAL
logging.level.root=WARN
logging.level.es.upm.miw=DEBUG

# Spring
spring.output.ansi.enabled=ALWAYS
spring.cache.type=none
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/base-app-weather
spring.main.web-application-type=reactive



logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.http.codec=TRACE

spring.cloud.gcp.firestore.enabled=true
spring.cloud.gcp.firestore.project-id=base-app-weather
spring.cloud.gcp.credentials.location=classpath:firebase-service-account.json


firebase.database.url=https://base-app-weather-default-rtdb.firebaseio.com/
firebase.api.key=AIzaSyBQ4F2VK9t0dza3J9YX5qvx2DXtinW8u5U
api.nominatim.base-url=https://nominatim.openstreetmap.org

# OpenWeatherMap Air Pollution API
api.openweathermap.air-pollution.base-url=http://api.openweathermap.org/data/2.5/air_pollution
api.openweathermap.api-key=acbf6241dcda326ab21b3cb52c58b151

# NASA APOD API Key (Usa "DEMO_KEY" para pruebas, o tu clave real)
nasa.apod.api.key=V1yy7vuJ9NEjNEQDVQrhEkDhacieBLzspglk8bSy